### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: api_server_textgenerationwebui

### ISSUE THREAD

**Issue by DutchEllie** [theroyallab/ST-tabbyAPI-loader#3]
After installing the extension in ST, I get the following error in the browser console:
![image](https://github.com/theroyallab/ST-tabbyAPI-loader/assets/6501187/df176caa-0c6a-42f9-b236-297c8e7e9be2)

This breaks all functionality, as the settings page for the app doesn't even show up in the extensions tab. 
This error is related to the import made in line 2 of the index.js script of this extension.

I am running the ST staging branch, but I assume that's not the issue since there is no difference between the staging and release branch at the moment that would specifically break this import.

**Comment by kingbri1** [comment]
Fixed in latest commits. Closing.
